--LISTA 6
SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTREQUEST;
SELECT * FROM CUSTOMER;
SELECT * FROM SUPPLIER;
SELECT * FROM REQUEST;

--EXERCICIO 1-A
DELETE FROM CUSTOMER
WHERE CDCUSTOMER NOT IN (SELECT CDCUSTOMER FROM REQUEST);

--EXERCICIO 1-B
DELETE FROM SUPPLIER
WHERE CDSUPPLIER NOT IN (SELECT CDSUPPLIER FROM PRODUCT);

--EXERCICIO 1-C
UPDATE PRODUCTREQUEST SET 
VLUNITARY = (SELECT VLPRICE FROM PRODUCT P WHERE P.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT);

--EXERCICIO 1-D
ALTER TABLE SUPPLIER
ADD DSSTATUS varchar(10);

--EXERCICIO 1-E
UPDATE SUPPLIER 
SET DSSTATUS = 'INATIVO'
WHERE CDSUPPLIER NOT IN (SELECT CDSUPPLIER FROM PRODUCT);

--EXERCICIO 1-F
UPDATE CUSTOMER
SET NMADRESS = 'DESCONHECIDO'
WHERE NMADRESS is null

--EXERCICIO 1-G
INSERT INTO PRODUCTREQUEST (CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
SELECT R.CDREQUEST, P.CDPRODUCT, 10, P.VLPRICE
FROM REQUEST R
CROSS JOIN PRODUCT P
WHERE NOT EXISTS (
    SELECT 1
    FROM PRODUCTREQUEST PR
    WHERE PR.CDPRODUCT = P.CDPRODUCT AND PR.CDREQUEST = R.CDREQUEST
);

--EXERCICIO 2-A
SELECT P.NMPRODUCT, C.NMCUSTOMER, COUNT(PR.CDPRODUCT) AS NUMVEZESCOMPRADO, SUM(PR.QTAMOUNT) AS QTDCOMPRADA, SUM(PR.VLUNITARY) AS TOTAL
FROM PRODUCTREQUEST PR
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
JOIN REQUEST R ON PR.CDREQUEST = R.CDREQUEST
JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
GROUP BY P.NMPRODUCT, C.NMCUSTOMER

--EXERCICIO 2-B
SELECT C.NMCUSTOMER, COUNT(R.CDCUSTOMER), SUM(R.VLTOTAL)
FROM REQUEST R
JOIN CUSTOMER C
ON C.CDCUSTOMER = R.CDCUSTOMER
WHERE R.CDCUSTOMER = C.CDCUSTOMER AND
YEAR (R.DTREQUEST) = 2003
GROUP BY C.NMCUSTOMER

--EXERCICIO 2-C
SELECT S.NMSUPPLIER, S.IDFONE, P.NMPRODUCT, P.VLPRICE, P.QTSTOCK
FROM SUPPLIER S
LEFT JOIN PRODUCT P 
ON S.CDSUPPLIER = P.CDSUPPLIER

--EXERCICIO 2-D
SELECT C.NMCUSTOMER, R.DTREQUEST, R.VLTOTAL
FROM CUSTOMER C
LEFT JOIN REQUEST R
ON C.CDCUSTOMER = R.CDCUSTOMER