--LISTA 1 
--EXERCICIO A

CREATE TABLE CUSTOMER(
	CDCUSTOMER INT IDENTITY(1,1),
	NMCUSTOMER VARCHAR(255),
	NRFONE NUMERIC(10, 2),
	DSADRESS VARCHAR(255)
);

ALTER TABLE CUSTOMER ALTER COLUMN NMCUSTOMER VARCHAR(255);

CREATE TABLE SUPLIER(
	CDSUPLIER INT IDENTITY(1,1),
	NMSUPLIER NUMERIC(10,2),
	NRFONE NUMERIC(10,2)
);

CREATE TABLE REQUEST(
	CDREQUEST INT IDENTITY(1,1),
	DTREQUEST DATETIME,
	CDCUSTOMER INT,
	DTDELIVER DATETIME,
	VLTOTAL NUMERIC(20,2)
);

CREATE TABLE PRODUCT(
	CDPRODUCT INT IDENTITY(1,1),
	NMPRODUCT VARCHAR(255),
	CDSUPLIER INT,
	VLPRICE NUMERIC(10,0),
	QTSTOCK INT
);

CREATE TABLE PRODUCTREQUEST(
	CDREQUEST INT NOT NULL,
	CDPRODUCT INT NOT NULL,
	QTAMOUNT NUMERIC(10,0),
	VLUNITARY NUMERIC(20,2)
);

DROP TABLE PRODUCTREQUEST

--EXERCICIO B
ALTER TABLE CUSTOMER ADD CONSTRAINT PKcustomer PRIMARY KEY (CDCUSTOMER);

ALTER TABLE SUPLIER ADD CONSTRAINT PKsuplier PRIMARY KEY (CDSUPLIER);

ALTER TABLE PRODUCT ADD CONSTRAINT PKproduct PRIMARY KEY (CDPRODUCT);

ALTER TABLE REQUEST ADD CONSTRAINT PKrequest PRIMARY KEY (CDREQUEST);

ALTER TABLE PRODUCTREQUEST ADD CONSTRAINT PKprodrequest PRIMARY KEY (CDREQUEST, CDPRODUCT);

--EXERCICIO C
ALTER TABLE REQUEST ADD CONSTRAINT FKcustomer FOREIGN KEY (CDCUSTOMER) REFERENCES CUSTOMER(CDCUSTOMER);

ALTER TABLE PRODUCT ADD CONSTRAINT FKsuplier FOREIGN KEY (CDSUPLIER) REFERENCES SUPLIER(CDSUPLIER);

ALTER TABLE PRODUCTREQUEST ADD CONSTRAINT FKcustomer FOREIGN KEY (CDREQUEST) REFERENCES REQUEST(CDREQUEST);

ALTER TABLE PRODUCTREQUEST ADD CONSTRAINT FKproduct FOREIGN KEY (CDPRODUCT) REFERENCES PRODUCT(CDPRODUCT);

--ECERCICIO D
CREATE INDEX INDEXFKPRODUCT ON PRODUCT (CDSUPLIER);

--EXERCICIO E
CREATE INDEX INDEXFKREQUEST ON REQUEST(CDCUSTOMER);

--EXERCICICIO F
ALTER TABLE SUPLIER ADD ADRESS VARCHAR(255)

--EXERCICIO G
INSERT INTO CUSTOMER (NMCUSTOMER, NRFONE, DSADRESS) VALUES ('Fabiano', 99879375, 'Rua Tijucas,110,Centro,Joinville - SC');
SELECT * FROM CUSTOMER

--EXERCICIO H
INSERT INTO REQUEST (DTREQUEST, CDCUSTOMER, DTDELIVER, VLTOTAL) VALUES (2008-01-31, 3, '2008-02-05', 54.00);

--EXERCICIO I
UPDATE CUSTOMER SET NRFONE = 99012567 WHERE NMCUSTOMER = 'Fabiano';
UPDATE CUSTOMER SET NRFONE = 99012567 WHERE CDCUSTOMER = 1;

--EXERCICIO J
DELETE FROM CUSTOMER WHERE CDCUSTOMER = 1;
DELETE FROM REQUEST WHERE CDREQUEST = 1;

DELETE FROM REQUEST WHERE CDCUSTOMER = 3;
DELETE FROM CUSTOMER WHERE NMCUSTOMER  = 'Fabiano';

--EXERCICIO K
DROP TABLE IF EXISTS PRODUCTREQUEST, REQUEST, PRODUCT, CUSTOMER, SUPLIER;

--DESSE JEITO N RPECISA SER NA ORDEM 
SET FOREIGN_KET_CHECKS 0;
DROP TABLE IF EXISTS PRODUCTREQUEST, REQUEST, PRODUCT, CUSTOMER, SUPLIER;
SET FOREIGN_KET_CHECKS 1;