--LISTA 7
SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTREQUEST;
SELECT * FROM CUSTOMER;
SELECT * FROM SUPPLIER;
SELECT * FROM REQUEST;

--EXERCICIO A
--N SEI SE O TOTAL SERIA O QTAMOUNT*VLUNITARY OU O VLTOTAL, VO IR PELO VLTOTAL
DELETE PR FROM PRODUCTREQUEST PR
JOIN REQUEST R ON PR.CDREQUEST = R.CDREQUEST
LEFT JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
WHERE R.VLTOTAL < 1000
AND MONTH(DTREQUEST) = 6
AND P.CDPRODUCT IS NULL;
--COALESCE(PR.QTAMOUNT, PR.VLUNITARY, R.DTREQUEST, DTDELIVER) IS NULL;

--EXERCICIO B
UPDATE PRODUCT
SET PRODUCT.VLPRICE = ( SELECT AVG(PR.VLUNITARY)
						FROM PRODUCTREQUEST PR
						WHERE PR.CDPRODUCT = PRODUCT.CDPRODUCT 
						HAVING SUM(PR.QTAMOUNT) < 800
					  );

--EXERCICIO C
INSERT INTO CUSTOMER (CDCUSTOMER, NMCUSTOMER, IDFONE)
SELECT (SELECT MAX(CDCUSTOMER) FROM CUSTOMER) + CDSUPPLIER, NMSUPPLIER, IDFONE
FROM SUPPLIER;

--EXERCICIO D
UPDATE REQUEST
SET DTDELIVER = 
DATEADD(MONTH, 1 , DTDELIVER) 
WHERE DTDELIVER >= DATEADD(DAY, 10, DTREQUEST)
AND VLTOTAL < 10000
;