--LISTA 3
SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTREQUEST;
SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCT;
SELECT * FROM SUPPLIER;

--EXERCICICO A
SELECT P.NMPRODUCT, S.NMSUPPLIER, P.VLPRICE*0.9 AS 'PRICE10%',
P.VLPRICE*0.8 AS 'PRICE20%', P.VLPRICE*0.7 AS 'PRICE30%'
FROM PRODUCT P JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
WHERE  P.VLPRICE*09 > 15;

--EXERCICIO B
--NOME PROD, NOME SUP, PRECO PROD, PRECO TOTAL ESTOQUE, PRECO PARA O DOBRODE ESTOQUE EM PROD QUE O PRECO TOTAL > 12000, ORDER BY FORNECEDOR
--PODIA TER CRIADO UMA VARIAVEL NESSE AQUI EU ACHO AO INVEZ DE FAZER A MULT SEMPRE 

SELECT P.NMPRODUCT, S.NMSUPPLIER, P.VLPRICE, P.VLPRICE*P.QTSTOCK AS PRICESTOCK, P.VLPRICE*(P.QTSTOCK*2) AS PRICESTOCKX2
FROM PRODUCT P JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
WHERE P.VLPRICE*P.QTSTOCK > 12000
ORDER BY S.NMSUPPLIER;

--ECERCICCIO C
--TEL CLIENTE CADASTRADO, COMECA COM J, ORDER BY NAME
SELECT * FROM CUSTOMER WHERE IDFONE IS NOT NULL AND NMCUSTOMER LIKE 'J%' ORDER BY NMCUSTOMER;

--EXERCICIO D
--NOME PROD, PREC, SUP NAME, WHER ESUP NAME LIKE ica ORDER BY PRCIE 
SELECT P.NMPRODUCT, P.VLPRICE, S.NMSUPPLIER
FROM PRODUCT P JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
WHERE S.NMSUPPLIER LIKE '%ica%'
ORDER BY S.NMSUPPLIER;

--EXERCICIO E
--S NAME, TEL SUP, PROD NAME, PROD PRICE, PRECO TOTAL STOCK PARA PROD QUE COMECE COM LETRA S E PRECO ACIMA DE 50, ORDER BY SUP E PRICE
SELECT S.NMSUPPLIER, S.IDFONE, P.NMPRODUCT, P.VLPRICE, P.VLPRICE*P.QTSTOCK AS TOTALSTOCK
FROM PRODUCT P JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
WHERE P.NMPRODUCT LIKE 'S%'
AND P.VLPRICE > 50
ORDER BY S.NMSUPPLIER, P.VLPRICE;

--EXERCICIO F
--CUST NAME, PROD NAME, REQUEST DATE, DELIVER DATE, QTD REQUEST, UNIT $, $ TOTAL, ONDE UNIT PEDIDO < 600 E DATA AGOSTO DE 2003, PROD COMECA COM LETRA M
SELECT C.NMCUSTOMER, P.NMPRODUCT, R.DTREQUEST, R.DTDELIVER, PR.QTAMOUNT, PR.VLUNITARY, PR.QTAMOUNT*PR.VLUNITARY AS TOTAL
FROM PRODUCTREQUEST PR 
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
JOIN REQUEST R ON PR.CDREQUEST = R.CDREQUEST
JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
WHERE PR.QTAMOUNT < 600 AND
R.DTREQUEST BETWEEN '2003-01-08' AND '2003-31-08' AND
P.NMPRODUCT LIKE 'M%';

--EXERCICIO G
SELECT C.NMCUSTOMER,P.NMPRODUCT, S.NMSUPPLIER, R.DTREQUEST, R.DTDELIVER, PR.VLUNITARY
FROM PRODUCTREQUEST PR 
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
JOIN REQUEST R ON PR.CDREQUEST = R.CDREQUEST
JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
WHERE S.IDFONE LIKE '(011)%' AND
PR.VLUNITARY > 20;