--LISTA 2
SELECT * FROM CUSTOMER;
SELECT * FROM REQUEST;
SELECT * FROM SUPPLIER;
SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTREQUEST;
--EXERCICIO A
SELECT NMCUSTOMER, IDFONE FROM CUSTOMER WHERE IDFONE LIKE '4%';

--EXERCICIO B
SELECT * FROM CUSTOMER WHERE IDFONE = NULL OR IDFONE = '';

--EXERCICIO C
SELECT * FROM SUPPLIER WHERE IDFONE NOT LIKE '%(%';

--EXERCICIO D
SELECT NMPRODUCT, QTSTOCK, (VLPRICE*0.9) FROM PRODUCT WHERE QTSTOCK > 2000;

--EXERCICIO E
SELECT NMPRODUCT, VLPRICE FROM PRODUCT WHERE VLPRICE BETWEEN 10 AND 20;

--EXERCICIO F
--BOTEI O IGUAL SÓ PRA RETORAR ALGUMA COISA E EU VER
SELECT NMPRODUCT, VLPRICE, VLPRICE*QTSTOCK AS TOTALSTOCK FROM PRODUCT WHERE VLPRICE >= 50;

--EXERCICIO G
SELECT PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE 
FROM PRODUCT JOIN SUPPLIER 
ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE PRODUCT.VLPRICE > 20 AND PRODUCT.QTSTOCK > 1500;

--EXERCICIO H
--MDS TINHA Q USAR EM PORTUGUES ISSO PRA QUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
SELECT REQUEST.VLTOTAL, REQUEST.DTREQUEST, CUSTOMER.NMCUSTOMER 
FROM REQUEST 
JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER 
WHERE REQUEST.DTREQUEST BETWEEN '2003-01-06' AND '2003-31-07'; 

--EXERCICCIO I
SELECT C.NMCUSTOMER, P.NMPRODUCT, R.DTREQUEST, PR.QTAMOUNT, PR.VLUNITARY, PR.QTAMOUNT*PR.VLUNITARY AS TOTAL
FROM PRODUCTREQUEST PR 
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT 
JOIN REQUEST R ON PR.CDREQUEST = R.CDREQUEST
JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
WHERE PR.QTAMOUNT > 500;
