--LISTA 4
SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTREQUEST;
SELECT * FROM CUSTOMER;
SELECT * FROM SUPPLIER;
SELECT * FROM REQUEST;

--EXERCICIO A
SELECT DISTINCT P.NMPRODUCT FROM PRODUCTREQUEST PR
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT;

SELECT P.NMPRODUCT FROM PRODUCTREQUEST PR
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
GROUP BY P.NMPRODUCT;

--EXERCICIO B
SELECT P.NMPRODUCT, COUNT(PR.CDPRODUCT) AS NUMBEROFREQUESTS, SUM(QTAMOUNT) AS AMOUNTBOUGHT FROM PRODUCTREQUEST PR
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT GROUP BY P.NMPRODUCT;

SELECT CDPRODUCT, COUNT(CDPRODUCT) FROM PRODUCTREQUEST GROUP BY CDPRODUCT;

--EXERCICIO C
--SUP NAME, TOTALSTOCK DO FORNECEDOR, MEDIA PRECO, E QUANTOS PROD FORNECE 
SELECT S.NMSUPPLIER, SUM(P.QTSTOCK) AS QTSTOCK, AVG(P.VLPRICE) AS ACGPRICE, COUNT(P.CDPRODUCT) AS HOWMANYPROD
FROM PRODUCT P JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER GROUP BY S.NMSUPPLIER;

--EXERCICIO D
SELECT C.NMCUSTOMER, C.IDFONE, MAX(R.VLTOTAL) AS MOSTEXPENSIVEBY, MIN(R.VLTOTAL) AS CHEAPERREQUEST, SUM(R.VLTOTAL) AS TOTALREQUESTED, AVG(R.VLTOTAL) AS AVGBUY 
FROM REQUEST R JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
GROUP BY C.NMCUSTOMER, C.IDFONE
ORDER BY MAX(R.VLTOTAL) DESC;

--EXERCICIO E
--DATA PEDIDO, NOME CLIETNE, PRODUTOS DESTINTOS PEDIU, VALOR TOTAL (PRODREQUEST), MEDIA DOS VALORES(PRODREQUEST), ORDER BY QTD PROD DISTINTO
SELECT R.DTREQUEST, C.NMCUSTOMER, COUNT(PR.CDPRODUCT) AS DISTINCTPRODUCTS, SUM(PR.VLUNITARY*PR.QTAMOUNT) AS SUMOFPURCHASES, AVG(PR.QTAMOUNT*PR.VLUNITARY) AS AVGBUY
FROM PRODUCTREQUEST PR
JOIN REQUEST R ON PR.CDPRODUCT = R.CDCUSTOMER
JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
GROUP BY C.NMCUSTOMER, R.DTREQUEST
ORDER BY DISTINCTPRODUCTS;

--EXERCICIO F
SELECT S.NMSUPPLIER, COUNT(P.CDSUPPLIER) AS DISTINCTPROD
FROM PRODUCT P JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
WHERE P.CDSUPPLIER > 1
GROUP BY S.NMSUPPLIER ;

--EXERCICIO G
--NOME PROD , NUM VEZES PEDIDO, QTD TOTAL PARA PEDIDOS PEDIDOS MENOS DE 2 VEZES
SELECT P.NMPRODUCT, COUNT(PR.CDPRODUCT) AS NUMREQUESTS, SUM(PR.QTAMOUNT) AS TOTALAMOUNT
FROM PRODUCT P
JOIN PRODUCTREQUEST PR ON P.CDPRODUCT = PR.CDPRODUCT
GROUP BY P.NMPRODUCT
HAVING  COUNT(PR.CDPRODUCT) < 2;

--EXERCICIO H
SELECT C.NMCUSTOMER, P.NMPRODUCT, SUM(P.VLPRICE) AS VALORGASTO, COUNT(PR.CDPRODUCT) AS QTDPEDIDA, S.NMSUPPLIER
FROM PRODUCTREQUEST PR 
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
JOIN REQUEST R ON PR.CDREQUEST = R.CDREQUEST
JOIN CUSTOMER C ON C.CDCUSTOMER = R.CDCUSTOMER
GROUP BY C.NMCUSTOMER, P.NMPRODUCT, S.NMSUPPLIER
HAVING SUM(P.VLPRICE) > 1000
ORDER BY C.NMCUSTOMER, P.NMPRODUCT;