--LISTA 5
SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTREQUEST;
SELECT * FROM CUSTOMER;
SELECT * FROM SUPPLIER;
SELECT * FROM REQUEST;

--EXERCICIO A
SELECT P.NMPRODUCT, COUNT(PR.CDPRODUCT)
FROM PRODUCT P
LEFT JOIN PRODUCTREQUEST PR
ON P.CDPRODUCT = PR.CDPRODUCT
GROUP BY P.NMPRODUCT

--EXERCICIO B
SELECT S.NMSUPPLIER, COUNT(P.CDSUPPLIER) AS PRODUTOSFORNECIDOS
FROM SUPPLIER S
LEFT JOIN PRODUCT P
ON S.CDSUPPLIER = P.CDSUPPLIER
GROUP BY S.NMSUPPLIER

--EXERCICIO C
SELECT S.NMSUPPLIER, P.NMPRODUCT, SUM(PR.QTAMOUNT) AS AMOUNTSOLD
FROM PRODUCTREQUEST PR
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
GROUP BY S.NMSUPPLIER, P.NMPRODUCT
UNION
SELECT 'TOTAL GERAL', '', SUM(QTAMOUNT) FROM PRODUCTREQUEST

--EXERCICIO D
SELECT C.NMCUSTOMER, P.NMPRODUCT, SUM(R.VLTOTAL) AS TOTALSPENDPERPROD
FROM CUSTOMER C 
JOIN REQUEST R ON R.CDCUSTOMER = C .CDCUSTOMER
JOIN PRODUCTREQUEST PR ON PR.CDREQUEST = R.CDREQUEST
JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
GROUP BY C.NMCUSTOMER, P.NMPRODUCT
UNION
SELECT 'TOTAL GERAL', '', SUM(VLTOTAL) FROM REQUEST

--EXERCICIO E
SELECT NMCUSTOMER, IDFONE FROM CUSTOMER
WHERE CDCUSTOMER NOT IN (SELECT CDCUSTOMER FROM REQUEST);

--EXERCICIO F
SELECT S.NMSUPPLIER, S.IDFONE FROM SUPPLIER S
JOIN PRODUCT P ON S.CDSUPPLIER = P.CDSUPPLIER 
WHERE P.NMPRODUCT IN('leite em po', 'agua mineral')
GROUP BY S.NMSUPPLIER, S.IDFONE
HAVING COUNT(DISTINCT P.NMPRODUCT) = 2

--EXERCICIO G
SELECT S.NMSUPPLIER FROM SUPPLIER S
JOIN PRODUCT P ON P.CDSUPPLIER = S.CDSUPPLIER
JOIN PRODUCTREQUEST PR ON PR.CDPRODUCT = P.CDPRODUCT
GROUP BY S.NMSUPPLIER
HAVING COUNT(PR.CDPRODUCT) > 3;